name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-format:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    
    env:
      SECRET_STRIPE_API_KEY: ${{ secrets.SECRET_STRIPE_API_KEY || 'dummy-key-for-ci' }}
      PUBLIC_STRIPE_API_KEY: ${{ secrets.PUBLIC_STRIPE_API_KEY || 'dummy-key-for-ci' }}
      VITE_GOOGLE_GEMINI_API_KEY: ${{ secrets.VITE_GOOGLE_GEMINI_API_KEY || 'dummy-key-for-ci' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
      
      - name: Check TypeScript
        run: npm run check

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    
    env:
      SECRET_STRIPE_API_KEY: ${{ secrets.SECRET_STRIPE_API_KEY || 'dummy-key-for-ci' }}
      PUBLIC_STRIPE_API_KEY: ${{ secrets.PUBLIC_STRIPE_API_KEY || 'dummy-key-for-ci' }}
      VITE_GOOGLE_GEMINI_API_KEY: ${{ secrets.VITE_GOOGLE_GEMINI_API_KEY || 'dummy-key-for-ci' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests with coverage
        run: npm run test:coverage
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: success()
        with:
          directory: ./coverage
          fail_ci_if_error: false
          verbose: true

  build:
    name: Build Check
    runs-on: ubuntu-latest
    
    env:
      SECRET_STRIPE_API_KEY: ${{ secrets.SECRET_STRIPE_API_KEY || 'dummy-key-for-ci' }}
      PUBLIC_STRIPE_API_KEY: ${{ secrets.PUBLIC_STRIPE_API_KEY || 'dummy-key-for-ci' }}
      VITE_GOOGLE_GEMINI_API_KEY: ${{ secrets.VITE_GOOGLE_GEMINI_API_KEY || 'dummy-key-for-ci' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
      
  # Add this status check job to report overall status
  status-check:
    name: Status Check
    needs: [lint-format, tests, build]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Check status
        run: |
          if [ "${{ contains(needs.*.result, 'failure') }}" = "true" ]; then
            echo "One or more jobs failed"
            exit 1
          else
            echo "All jobs passed"
            exit 0
          fi 